### ISSUE TITLE
Container does not map to any ports

### ISSUE THREAD

**Issue by Mailblocker** [dovecot/docker#4]
Hi,
I wanted to use this docker image and tried the following:

    docker run dovecot/dovecot:2.3.20

It is starting up the cotainer as expected but no ports are mapped to it and I am not able to connect to the IMAP interface.

    docker container ps

results in this:

    CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS          PORTS     NAMES
    db8193af8c60   dovecot/dovecot:2.3.20   "/usr/bin/tini -- /u…"   12 seconds ago   Up 11 seconds             eager_hodgkin

I expected a basic running IMAP server or am I wrong in this assumption?

**Comment by cmouse** [comment]
Seems we are missing EXPOSE statements, lets fix this.

**Comment by cmouse** [comment]
Fixed with 767418601ce4a470fda79f13a9253e31ae51908c and 2.3.20 refreshed. You still need to use -P (or --expose/-p) to actually expose the ports.

**Comment by Mailblocker** [comment]
The ports are now being exposed now but the connection does not work.

Shouldn't it be:
```
EXPOSE 24
EXPOSE 110
EXPOSE 143
EXPOSE 485
EXPOSE 587
EXPOSE 993
EXPOSE 995
EXPOSE 4190
```

instead of
```
EXPOSE 24
EXPOSE 110
EXPOSE 143
EXPOSE 485
EXPOSE 587
EXPOSE 990
EXPOSE 993
EXPOSE 4190
```
?

I am also wondering about the port 485 but that might be a needed one.

Anyway if I start the container with:
```
docker run -p 143:143 -p 110:110 -p 995:995 -p 993:993 -p 587:587 -p 24:24 -p 4190:4190 -p 485:485 -p 990:990  dovecot/dovecot:2.3.20
```

It starts and I am able to connect but the authentification does not work:
```
May 09 20:36:31 imap-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 3 secs): user=<test>, method=PLAIN, rip=192.168.2.24, lip=172.17.0.2, TLS, session=<UtO+tUj7sKbAqAIY>
```

On the client side (evolution mail) I am getting a prompt for the username and password.

Is there something missing in the default config to accept every connection?

**Comment by cmouse** [comment]
The default password, if you do not configure anything, is `pass`. You need to update the configuration if you want it to do something else.

For the EXPOSE and ports, please see https://docs.docker.com/config/containers/container-networking/#published-ports and https://docs.docker.com/engine/reference/builder/#expose

**Comment by Mailblocker** [comment]
Thank you @cmouse for the answer!

**Regarding the passwort**
I missed in the docu that password is `pass`. Sorry about that, I somehow thought any password could be used.

**Regarding the ports**
I get the EXPOSE part about the ports of a docker container. My point is:
In my opinion the commit https://github.com/dovecot/docker/commit/767418601ce4a470fda79f13a9253e31ae51908c exposes not the correct ports needed for dovecot when using the `-P` option.

If I start the container using:
docker run -P dovecot/dovecot:2.3.20

I see that the ports added in the last commit are exposed for the container, as shown here. But a connection is not possible.

When starting the container with (different ports than in the commit 995 instead of 990):
docker run -p 143:143 -p 110:110 -p 995:995 -p 993:993 -p 587:587 -p 24:24 -p 4190:4190 -p 485:485 -p 990:990  dovecot/dovecot:2.3.20

It starts up and is fully functional as expected. Maybe I'm not understanding the -P option correctly. But I thought using this option should expose all ports needed for the container to run.

**Comment by cmouse** [comment]
`-P - Publish all exposed ports to random ports`

**Comment by Mailblocker** [comment]
Thanks and sorry.
