### ISSUE TITLE
Allow config file to be extended

### ISSUE THREAD

**Issue by slusarz** [dovecot/docker#5]
Would be nice to be able to extend the image by simply adding an additional config file, instead of having to rewrite the existing file.

I think what is needed is:

1. Dockerfile: create /etc/dovecot/conf.d
2. Dockerfile: add "/etc/dovecot/conf.d" to VOLUME command
3. dovecot.conf: Add `!include conf.d/*.conf` at end of file

(Yes, I know dovecot config can be accessed via volume ... but being able to extend dovecot container image by adding an additional config file in new Dockerfile would be very useful...)

**Comment by cmouse** [comment]
Sure, we can add that.

**Comment by cmouse** [comment]
closed with c5bfd6b35c2509826c50a6ca7138348a6f013517
